---
abstract: 'Installer for bz2'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-bz2-Installer
requires:
  ExtUtils::CBuilder: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/Alien-bz2-Installer/issues
  homepage: http://perl.wdlabs.com/Alien-bz2-Installer
  repository: git://github.com/plicease/Alien-bz2-Installer.git
version: '0.05'
